// Generated by view binder compiler. Do not edit!
package com.example.vpark.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.vpark.R;
import com.google.android.material.appbar.AppBarLayout;
import com.google.android.material.appbar.MaterialToolbar;
import com.google.android.material.card.MaterialCardView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityViewTicketBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final AppBarLayout appBarLayout;

  @NonNull
  public final TextView noTicketMessageTextView;

  @NonNull
  public final LinearLayout noTicketView;

  @NonNull
  public final ImageView ownerQrImageView;

  @NonNull
  public final MaterialCardView qrCodeCardView;

  @NonNull
  public final MaterialToolbar toolbar;

  private ActivityViewTicketBinding(@NonNull ConstraintLayout rootView,
      @NonNull AppBarLayout appBarLayout, @NonNull TextView noTicketMessageTextView,
      @NonNull LinearLayout noTicketView, @NonNull ImageView ownerQrImageView,
      @NonNull MaterialCardView qrCodeCardView, @NonNull MaterialToolbar toolbar) {
    this.rootView = rootView;
    this.appBarLayout = appBarLayout;
    this.noTicketMessageTextView = noTicketMessageTextView;
    this.noTicketView = noTicketView;
    this.ownerQrImageView = ownerQrImageView;
    this.qrCodeCardView = qrCodeCardView;
    this.toolbar = toolbar;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityViewTicketBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityViewTicketBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_view_ticket, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityViewTicketBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.appBarLayout;
      AppBarLayout appBarLayout = ViewBindings.findChildViewById(rootView, id);
      if (appBarLayout == null) {
        break missingId;
      }

      id = R.id.noTicketMessageTextView;
      TextView noTicketMessageTextView = ViewBindings.findChildViewById(rootView, id);
      if (noTicketMessageTextView == null) {
        break missingId;
      }

      id = R.id.noTicketView;
      LinearLayout noTicketView = ViewBindings.findChildViewById(rootView, id);
      if (noTicketView == null) {
        break missingId;
      }

      id = R.id.ownerQrImageView;
      ImageView ownerQrImageView = ViewBindings.findChildViewById(rootView, id);
      if (ownerQrImageView == null) {
        break missingId;
      }

      id = R.id.qrCodeCardView;
      MaterialCardView qrCodeCardView = ViewBindings.findChildViewById(rootView, id);
      if (qrCodeCardView == null) {
        break missingId;
      }

      id = R.id.toolbar;
      MaterialToolbar toolbar = ViewBindings.findChildViewById(rootView, id);
      if (toolbar == null) {
        break missingId;
      }

      return new ActivityViewTicketBinding((ConstraintLayout) rootView, appBarLayout,
          noTicketMessageTextView, noTicketView, ownerQrImageView, qrCodeCardView, toolbar);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
