// Generated by view binder compiler. Do not edit!
package com.example.vpark.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.ScrollView;
import android.widget.Spinner;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.vpark.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.osmdroid.views.MapView;

public final class ActivityAddEditParkingLotBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final CheckBox isEnabledCheckBox;

  @NonNull
  public final EditText locationEditText;

  @NonNull
  public final MapView mapView;

  @NonNull
  public final EditText parkingLotIdEditText;

  @NonNull
  public final EditText parkingLotNameEditText;

  @NonNull
  public final EditText parkingTimeEditText;

  @NonNull
  public final EditText parkingTimeOutEditText;

  @NonNull
  public final Spinner parkingTypeSpinner;

  @NonNull
  public final EditText rateEditText;

  @NonNull
  public final Button saveParkingLotButton;

  @NonNull
  public final EditText totalSlotsEditText;

  private ActivityAddEditParkingLotBinding(@NonNull ScrollView rootView,
      @NonNull CheckBox isEnabledCheckBox, @NonNull EditText locationEditText,
      @NonNull MapView mapView, @NonNull EditText parkingLotIdEditText,
      @NonNull EditText parkingLotNameEditText, @NonNull EditText parkingTimeEditText,
      @NonNull EditText parkingTimeOutEditText, @NonNull Spinner parkingTypeSpinner,
      @NonNull EditText rateEditText, @NonNull Button saveParkingLotButton,
      @NonNull EditText totalSlotsEditText) {
    this.rootView = rootView;
    this.isEnabledCheckBox = isEnabledCheckBox;
    this.locationEditText = locationEditText;
    this.mapView = mapView;
    this.parkingLotIdEditText = parkingLotIdEditText;
    this.parkingLotNameEditText = parkingLotNameEditText;
    this.parkingTimeEditText = parkingTimeEditText;
    this.parkingTimeOutEditText = parkingTimeOutEditText;
    this.parkingTypeSpinner = parkingTypeSpinner;
    this.rateEditText = rateEditText;
    this.saveParkingLotButton = saveParkingLotButton;
    this.totalSlotsEditText = totalSlotsEditText;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityAddEditParkingLotBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityAddEditParkingLotBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_add_edit_parking_lot, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityAddEditParkingLotBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.isEnabledCheckBox;
      CheckBox isEnabledCheckBox = ViewBindings.findChildViewById(rootView, id);
      if (isEnabledCheckBox == null) {
        break missingId;
      }

      id = R.id.locationEditText;
      EditText locationEditText = ViewBindings.findChildViewById(rootView, id);
      if (locationEditText == null) {
        break missingId;
      }

      id = R.id.mapView;
      MapView mapView = ViewBindings.findChildViewById(rootView, id);
      if (mapView == null) {
        break missingId;
      }

      id = R.id.parkingLotIdEditText;
      EditText parkingLotIdEditText = ViewBindings.findChildViewById(rootView, id);
      if (parkingLotIdEditText == null) {
        break missingId;
      }

      id = R.id.parkingLotNameEditText;
      EditText parkingLotNameEditText = ViewBindings.findChildViewById(rootView, id);
      if (parkingLotNameEditText == null) {
        break missingId;
      }

      id = R.id.parkingTimeEditText;
      EditText parkingTimeEditText = ViewBindings.findChildViewById(rootView, id);
      if (parkingTimeEditText == null) {
        break missingId;
      }

      id = R.id.parkingTimeOutEditText;
      EditText parkingTimeOutEditText = ViewBindings.findChildViewById(rootView, id);
      if (parkingTimeOutEditText == null) {
        break missingId;
      }

      id = R.id.parkingTypeSpinner;
      Spinner parkingTypeSpinner = ViewBindings.findChildViewById(rootView, id);
      if (parkingTypeSpinner == null) {
        break missingId;
      }

      id = R.id.rateEditText;
      EditText rateEditText = ViewBindings.findChildViewById(rootView, id);
      if (rateEditText == null) {
        break missingId;
      }

      id = R.id.saveParkingLotButton;
      Button saveParkingLotButton = ViewBindings.findChildViewById(rootView, id);
      if (saveParkingLotButton == null) {
        break missingId;
      }

      id = R.id.totalSlotsEditText;
      EditText totalSlotsEditText = ViewBindings.findChildViewById(rootView, id);
      if (totalSlotsEditText == null) {
        break missingId;
      }

      return new ActivityAddEditParkingLotBinding((ScrollView) rootView, isEnabledCheckBox,
          locationEditText, mapView, parkingLotIdEditText, parkingLotNameEditText,
          parkingTimeEditText, parkingTimeOutEditText, parkingTypeSpinner, rateEditText,
          saveParkingLotButton, totalSlotsEditText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
