// Generated by view binder compiler. Do not edit!
package com.example.vpark.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.vpark.R;
import com.google.android.material.appbar.AppBarLayout;
import com.google.android.material.appbar.MaterialToolbar;
import com.google.android.material.card.MaterialCardView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityUserDashboardBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final AppBarLayout appBarLayout;

  @NonNull
  public final MaterialCardView billCard;

  @NonNull
  public final ImageView billIcon;

  @NonNull
  public final ImageView logoutButton;

  @NonNull
  public final MaterialCardView manageProfileCard;

  @NonNull
  public final ImageView profileIcon;

  @NonNull
  public final ImageView qrIcon;

  @NonNull
  public final MaterialCardView scanQrCard;

  @NonNull
  public final MaterialToolbar toolbar;

  private ActivityUserDashboardBinding(@NonNull ConstraintLayout rootView,
      @NonNull AppBarLayout appBarLayout, @NonNull MaterialCardView billCard,
      @NonNull ImageView billIcon, @NonNull ImageView logoutButton,
      @NonNull MaterialCardView manageProfileCard, @NonNull ImageView profileIcon,
      @NonNull ImageView qrIcon, @NonNull MaterialCardView scanQrCard,
      @NonNull MaterialToolbar toolbar) {
    this.rootView = rootView;
    this.appBarLayout = appBarLayout;
    this.billCard = billCard;
    this.billIcon = billIcon;
    this.logoutButton = logoutButton;
    this.manageProfileCard = manageProfileCard;
    this.profileIcon = profileIcon;
    this.qrIcon = qrIcon;
    this.scanQrCard = scanQrCard;
    this.toolbar = toolbar;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityUserDashboardBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityUserDashboardBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_user_dashboard, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityUserDashboardBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.appBarLayout;
      AppBarLayout appBarLayout = ViewBindings.findChildViewById(rootView, id);
      if (appBarLayout == null) {
        break missingId;
      }

      id = R.id.billCard;
      MaterialCardView billCard = ViewBindings.findChildViewById(rootView, id);
      if (billCard == null) {
        break missingId;
      }

      id = R.id.billIcon;
      ImageView billIcon = ViewBindings.findChildViewById(rootView, id);
      if (billIcon == null) {
        break missingId;
      }

      id = R.id.logoutButton;
      ImageView logoutButton = ViewBindings.findChildViewById(rootView, id);
      if (logoutButton == null) {
        break missingId;
      }

      id = R.id.manageProfileCard;
      MaterialCardView manageProfileCard = ViewBindings.findChildViewById(rootView, id);
      if (manageProfileCard == null) {
        break missingId;
      }

      id = R.id.profileIcon;
      ImageView profileIcon = ViewBindings.findChildViewById(rootView, id);
      if (profileIcon == null) {
        break missingId;
      }

      id = R.id.qrIcon;
      ImageView qrIcon = ViewBindings.findChildViewById(rootView, id);
      if (qrIcon == null) {
        break missingId;
      }

      id = R.id.scanQrCard;
      MaterialCardView scanQrCard = ViewBindings.findChildViewById(rootView, id);
      if (scanQrCard == null) {
        break missingId;
      }

      id = R.id.toolbar;
      MaterialToolbar toolbar = ViewBindings.findChildViewById(rootView, id);
      if (toolbar == null) {
        break missingId;
      }

      return new ActivityUserDashboardBinding((ConstraintLayout) rootView, appBarLayout, billCard,
          billIcon, logoutButton, manageProfileCard, profileIcon, qrIcon, scanQrCard, toolbar);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
