// Generated by view binder compiler. Do not edit!
package com.example.vpark.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.vpark.R;
import com.google.android.material.button.MaterialButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityAdminRegisterBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final TextView adminLoginTitle;

  @NonNull
  public final ImageView backArrow;

  @NonNull
  public final EditText emailEditText;

  @NonNull
  public final TextView loginTextView;

  @NonNull
  public final EditText nameEditText;

  @NonNull
  public final EditText passwordEditText;

  @NonNull
  public final MaterialButton registerButton;

  @NonNull
  public final EditText telephoneEditText;

  private ActivityAdminRegisterBinding(@NonNull ConstraintLayout rootView,
      @NonNull TextView adminLoginTitle, @NonNull ImageView backArrow,
      @NonNull EditText emailEditText, @NonNull TextView loginTextView,
      @NonNull EditText nameEditText, @NonNull EditText passwordEditText,
      @NonNull MaterialButton registerButton, @NonNull EditText telephoneEditText) {
    this.rootView = rootView;
    this.adminLoginTitle = adminLoginTitle;
    this.backArrow = backArrow;
    this.emailEditText = emailEditText;
    this.loginTextView = loginTextView;
    this.nameEditText = nameEditText;
    this.passwordEditText = passwordEditText;
    this.registerButton = registerButton;
    this.telephoneEditText = telephoneEditText;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityAdminRegisterBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityAdminRegisterBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_admin_register, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityAdminRegisterBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.adminLoginTitle;
      TextView adminLoginTitle = ViewBindings.findChildViewById(rootView, id);
      if (adminLoginTitle == null) {
        break missingId;
      }

      id = R.id.backArrow;
      ImageView backArrow = ViewBindings.findChildViewById(rootView, id);
      if (backArrow == null) {
        break missingId;
      }

      id = R.id.emailEditText;
      EditText emailEditText = ViewBindings.findChildViewById(rootView, id);
      if (emailEditText == null) {
        break missingId;
      }

      id = R.id.loginTextView;
      TextView loginTextView = ViewBindings.findChildViewById(rootView, id);
      if (loginTextView == null) {
        break missingId;
      }

      id = R.id.nameEditText;
      EditText nameEditText = ViewBindings.findChildViewById(rootView, id);
      if (nameEditText == null) {
        break missingId;
      }

      id = R.id.passwordEditText;
      EditText passwordEditText = ViewBindings.findChildViewById(rootView, id);
      if (passwordEditText == null) {
        break missingId;
      }

      id = R.id.registerButton;
      MaterialButton registerButton = ViewBindings.findChildViewById(rootView, id);
      if (registerButton == null) {
        break missingId;
      }

      id = R.id.telephoneEditText;
      EditText telephoneEditText = ViewBindings.findChildViewById(rootView, id);
      if (telephoneEditText == null) {
        break missingId;
      }

      return new ActivityAdminRegisterBinding((ConstraintLayout) rootView, adminLoginTitle,
          backArrow, emailEditText, loginTextView, nameEditText, passwordEditText, registerButton,
          telephoneEditText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
