// Generated by view binder compiler. Do not edit!
package com.example.vpark.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.vpark.R;
import com.google.android.material.button.MaterialButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivitySecondBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final MaterialButton adminLoginBtn;

  @NonNull
  public final ImageView backArrow;

  @NonNull
  public final ConstraintLayout topSection;

  @NonNull
  public final MaterialButton userLoginBtn;

  private ActivitySecondBinding(@NonNull ConstraintLayout rootView,
      @NonNull MaterialButton adminLoginBtn, @NonNull ImageView backArrow,
      @NonNull ConstraintLayout topSection, @NonNull MaterialButton userLoginBtn) {
    this.rootView = rootView;
    this.adminLoginBtn = adminLoginBtn;
    this.backArrow = backArrow;
    this.topSection = topSection;
    this.userLoginBtn = userLoginBtn;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivitySecondBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivitySecondBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_second, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivitySecondBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.adminLoginBtn;
      MaterialButton adminLoginBtn = ViewBindings.findChildViewById(rootView, id);
      if (adminLoginBtn == null) {
        break missingId;
      }

      id = R.id.backArrow;
      ImageView backArrow = ViewBindings.findChildViewById(rootView, id);
      if (backArrow == null) {
        break missingId;
      }

      id = R.id.topSection;
      ConstraintLayout topSection = ViewBindings.findChildViewById(rootView, id);
      if (topSection == null) {
        break missingId;
      }

      id = R.id.userLoginBtn;
      MaterialButton userLoginBtn = ViewBindings.findChildViewById(rootView, id);
      if (userLoginBtn == null) {
        break missingId;
      }

      return new ActivitySecondBinding((ConstraintLayout) rootView, adminLoginBtn, backArrow,
          topSection, userLoginBtn);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
