// Generated by view binder compiler. Do not edit!
package com.example.vpark.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.vpark.R;
import com.google.android.material.appbar.AppBarLayout;
import com.google.android.material.appbar.MaterialToolbar;
import com.google.android.material.button.MaterialButton;
import com.google.android.material.card.MaterialCardView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityBillReportBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final AppBarLayout appBarLayout;

  @NonNull
  public final RecyclerView billReportRecyclerView;

  @NonNull
  public final MaterialButton scanToFinalizeButton;

  @NonNull
  public final MaterialCardView summaryCard;

  @NonNull
  public final MaterialToolbar toolbar;

  @NonNull
  public final TextView totalRevenueTextView;

  @NonNull
  public final TextView totalTransactionsTextView;

  @NonNull
  public final TextView transactionHistoryLabel;

  private ActivityBillReportBinding(@NonNull ConstraintLayout rootView,
      @NonNull AppBarLayout appBarLayout, @NonNull RecyclerView billReportRecyclerView,
      @NonNull MaterialButton scanToFinalizeButton, @NonNull MaterialCardView summaryCard,
      @NonNull MaterialToolbar toolbar, @NonNull TextView totalRevenueTextView,
      @NonNull TextView totalTransactionsTextView, @NonNull TextView transactionHistoryLabel) {
    this.rootView = rootView;
    this.appBarLayout = appBarLayout;
    this.billReportRecyclerView = billReportRecyclerView;
    this.scanToFinalizeButton = scanToFinalizeButton;
    this.summaryCard = summaryCard;
    this.toolbar = toolbar;
    this.totalRevenueTextView = totalRevenueTextView;
    this.totalTransactionsTextView = totalTransactionsTextView;
    this.transactionHistoryLabel = transactionHistoryLabel;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityBillReportBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityBillReportBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_bill_report, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityBillReportBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.appBarLayout;
      AppBarLayout appBarLayout = ViewBindings.findChildViewById(rootView, id);
      if (appBarLayout == null) {
        break missingId;
      }

      id = R.id.billReportRecyclerView;
      RecyclerView billReportRecyclerView = ViewBindings.findChildViewById(rootView, id);
      if (billReportRecyclerView == null) {
        break missingId;
      }

      id = R.id.scanToFinalizeButton;
      MaterialButton scanToFinalizeButton = ViewBindings.findChildViewById(rootView, id);
      if (scanToFinalizeButton == null) {
        break missingId;
      }

      id = R.id.summaryCard;
      MaterialCardView summaryCard = ViewBindings.findChildViewById(rootView, id);
      if (summaryCard == null) {
        break missingId;
      }

      id = R.id.toolbar;
      MaterialToolbar toolbar = ViewBindings.findChildViewById(rootView, id);
      if (toolbar == null) {
        break missingId;
      }

      id = R.id.totalRevenueTextView;
      TextView totalRevenueTextView = ViewBindings.findChildViewById(rootView, id);
      if (totalRevenueTextView == null) {
        break missingId;
      }

      id = R.id.totalTransactionsTextView;
      TextView totalTransactionsTextView = ViewBindings.findChildViewById(rootView, id);
      if (totalTransactionsTextView == null) {
        break missingId;
      }

      id = R.id.transactionHistoryLabel;
      TextView transactionHistoryLabel = ViewBindings.findChildViewById(rootView, id);
      if (transactionHistoryLabel == null) {
        break missingId;
      }

      return new ActivityBillReportBinding((ConstraintLayout) rootView, appBarLayout,
          billReportRecyclerView, scanToFinalizeButton, summaryCard, toolbar, totalRevenueTextView,
          totalTransactionsTextView, transactionHistoryLabel);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
