// Generated by view binder compiler. Do not edit!
package com.example.vpark.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.vpark.R;
import com.google.android.material.appbar.AppBarLayout;
import com.google.android.material.appbar.MaterialToolbar;
import com.google.android.material.card.MaterialCardView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityBillBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final AppBarLayout appBarLayout;

  @NonNull
  public final TextView historyLabel;

  @NonNull
  public final MaterialCardView summaryCard;

  @NonNull
  public final MaterialToolbar toolbar;

  @NonNull
  public final TextView totalSessionsTextView;

  @NonNull
  public final TextView totalSpentTextView;

  @NonNull
  public final RecyclerView userBillRecyclerView;

  private ActivityBillBinding(@NonNull ConstraintLayout rootView,
      @NonNull AppBarLayout appBarLayout, @NonNull TextView historyLabel,
      @NonNull MaterialCardView summaryCard, @NonNull MaterialToolbar toolbar,
      @NonNull TextView totalSessionsTextView, @NonNull TextView totalSpentTextView,
      @NonNull RecyclerView userBillRecyclerView) {
    this.rootView = rootView;
    this.appBarLayout = appBarLayout;
    this.historyLabel = historyLabel;
    this.summaryCard = summaryCard;
    this.toolbar = toolbar;
    this.totalSessionsTextView = totalSessionsTextView;
    this.totalSpentTextView = totalSpentTextView;
    this.userBillRecyclerView = userBillRecyclerView;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityBillBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityBillBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_bill, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityBillBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.appBarLayout;
      AppBarLayout appBarLayout = ViewBindings.findChildViewById(rootView, id);
      if (appBarLayout == null) {
        break missingId;
      }

      id = R.id.historyLabel;
      TextView historyLabel = ViewBindings.findChildViewById(rootView, id);
      if (historyLabel == null) {
        break missingId;
      }

      id = R.id.summaryCard;
      MaterialCardView summaryCard = ViewBindings.findChildViewById(rootView, id);
      if (summaryCard == null) {
        break missingId;
      }

      id = R.id.toolbar;
      MaterialToolbar toolbar = ViewBindings.findChildViewById(rootView, id);
      if (toolbar == null) {
        break missingId;
      }

      id = R.id.totalSessionsTextView;
      TextView totalSessionsTextView = ViewBindings.findChildViewById(rootView, id);
      if (totalSessionsTextView == null) {
        break missingId;
      }

      id = R.id.totalSpentTextView;
      TextView totalSpentTextView = ViewBindings.findChildViewById(rootView, id);
      if (totalSpentTextView == null) {
        break missingId;
      }

      id = R.id.userBillRecyclerView;
      RecyclerView userBillRecyclerView = ViewBindings.findChildViewById(rootView, id);
      if (userBillRecyclerView == null) {
        break missingId;
      }

      return new ActivityBillBinding((ConstraintLayout) rootView, appBarLayout, historyLabel,
          summaryCard, toolbar, totalSessionsTextView, totalSpentTextView, userBillRecyclerView);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
