// Generated by view binder compiler. Do not edit!
package com.example.vpark.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.Spinner;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.vpark.R;
import com.google.android.material.appbar.AppBarLayout;
import com.google.android.material.appbar.MaterialToolbar;
import com.google.android.material.button.MaterialButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityGenerateQrBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final ImageView adminQrImageView;

  @NonNull
  public final AppBarLayout appBarLayout;

  @NonNull
  public final LinearLayout formContainer;

  @NonNull
  public final MaterialButton generateQrButton;

  @NonNull
  public final Spinner ownerNameSpinner;

  @NonNull
  public final Spinner parkingTypeSpinner;

  @NonNull
  public final ImageView qrCodeImageView;

  @NonNull
  public final EditText ratePerHourEditText;

  @NonNull
  public final TextView scanLabel;

  @NonNull
  public final TextView timeInTextView;

  @NonNull
  public final TextView timeOutTextView;

  @NonNull
  public final MaterialToolbar toolbar;

  @NonNull
  public final EditText vehicleNumberEditText;

  @NonNull
  public final Spinner vehicleTypeSpinner;

  private ActivityGenerateQrBinding(@NonNull ScrollView rootView,
      @NonNull ImageView adminQrImageView, @NonNull AppBarLayout appBarLayout,
      @NonNull LinearLayout formContainer, @NonNull MaterialButton generateQrButton,
      @NonNull Spinner ownerNameSpinner, @NonNull Spinner parkingTypeSpinner,
      @NonNull ImageView qrCodeImageView, @NonNull EditText ratePerHourEditText,
      @NonNull TextView scanLabel, @NonNull TextView timeInTextView,
      @NonNull TextView timeOutTextView, @NonNull MaterialToolbar toolbar,
      @NonNull EditText vehicleNumberEditText, @NonNull Spinner vehicleTypeSpinner) {
    this.rootView = rootView;
    this.adminQrImageView = adminQrImageView;
    this.appBarLayout = appBarLayout;
    this.formContainer = formContainer;
    this.generateQrButton = generateQrButton;
    this.ownerNameSpinner = ownerNameSpinner;
    this.parkingTypeSpinner = parkingTypeSpinner;
    this.qrCodeImageView = qrCodeImageView;
    this.ratePerHourEditText = ratePerHourEditText;
    this.scanLabel = scanLabel;
    this.timeInTextView = timeInTextView;
    this.timeOutTextView = timeOutTextView;
    this.toolbar = toolbar;
    this.vehicleNumberEditText = vehicleNumberEditText;
    this.vehicleTypeSpinner = vehicleTypeSpinner;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityGenerateQrBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityGenerateQrBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_generate_qr, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityGenerateQrBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.adminQrImageView;
      ImageView adminQrImageView = ViewBindings.findChildViewById(rootView, id);
      if (adminQrImageView == null) {
        break missingId;
      }

      id = R.id.appBarLayout;
      AppBarLayout appBarLayout = ViewBindings.findChildViewById(rootView, id);
      if (appBarLayout == null) {
        break missingId;
      }

      id = R.id.formContainer;
      LinearLayout formContainer = ViewBindings.findChildViewById(rootView, id);
      if (formContainer == null) {
        break missingId;
      }

      id = R.id.generateQrButton;
      MaterialButton generateQrButton = ViewBindings.findChildViewById(rootView, id);
      if (generateQrButton == null) {
        break missingId;
      }

      id = R.id.ownerNameSpinner;
      Spinner ownerNameSpinner = ViewBindings.findChildViewById(rootView, id);
      if (ownerNameSpinner == null) {
        break missingId;
      }

      id = R.id.parkingTypeSpinner;
      Spinner parkingTypeSpinner = ViewBindings.findChildViewById(rootView, id);
      if (parkingTypeSpinner == null) {
        break missingId;
      }

      id = R.id.qrCodeImageView;
      ImageView qrCodeImageView = ViewBindings.findChildViewById(rootView, id);
      if (qrCodeImageView == null) {
        break missingId;
      }

      id = R.id.ratePerHourEditText;
      EditText ratePerHourEditText = ViewBindings.findChildViewById(rootView, id);
      if (ratePerHourEditText == null) {
        break missingId;
      }

      id = R.id.scanLabel;
      TextView scanLabel = ViewBindings.findChildViewById(rootView, id);
      if (scanLabel == null) {
        break missingId;
      }

      id = R.id.timeInTextView;
      TextView timeInTextView = ViewBindings.findChildViewById(rootView, id);
      if (timeInTextView == null) {
        break missingId;
      }

      id = R.id.timeOutTextView;
      TextView timeOutTextView = ViewBindings.findChildViewById(rootView, id);
      if (timeOutTextView == null) {
        break missingId;
      }

      id = R.id.toolbar;
      MaterialToolbar toolbar = ViewBindings.findChildViewById(rootView, id);
      if (toolbar == null) {
        break missingId;
      }

      id = R.id.vehicleNumberEditText;
      EditText vehicleNumberEditText = ViewBindings.findChildViewById(rootView, id);
      if (vehicleNumberEditText == null) {
        break missingId;
      }

      id = R.id.vehicleTypeSpinner;
      Spinner vehicleTypeSpinner = ViewBindings.findChildViewById(rootView, id);
      if (vehicleTypeSpinner == null) {
        break missingId;
      }

      return new ActivityGenerateQrBinding((ScrollView) rootView, adminQrImageView, appBarLayout,
          formContainer, generateQrButton, ownerNameSpinner, parkingTypeSpinner, qrCodeImageView,
          ratePerHourEditText, scanLabel, timeInTextView, timeOutTextView, toolbar,
          vehicleNumberEditText, vehicleTypeSpinner);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
