// Generated by view binder compiler. Do not edit!
package com.example.vpark.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.ProgressBar;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.vpark.R;
import com.google.android.material.appbar.AppBarLayout;
import com.google.android.material.appbar.MaterialToolbar;
import com.google.android.material.button.MaterialButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityUserLoginBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final AppBarLayout appBarLayout;

  @NonNull
  public final EditText emailEditText;

  @NonNull
  public final TextView forgotPasswordTextView;

  @NonNull
  public final EditText nameEditText;

  @NonNull
  public final EditText passwordEditText;

  @NonNull
  public final ProgressBar progressBar;

  @NonNull
  public final MaterialButton registerButton;

  @NonNull
  public final CheckBox rememberMeCheckBox;

  @NonNull
  public final TextView signInTextView;

  @NonNull
  public final EditText telephoneEditText;

  @NonNull
  public final MaterialToolbar toolbar;

  private ActivityUserLoginBinding(@NonNull ConstraintLayout rootView,
      @NonNull AppBarLayout appBarLayout, @NonNull EditText emailEditText,
      @NonNull TextView forgotPasswordTextView, @NonNull EditText nameEditText,
      @NonNull EditText passwordEditText, @NonNull ProgressBar progressBar,
      @NonNull MaterialButton registerButton, @NonNull CheckBox rememberMeCheckBox,
      @NonNull TextView signInTextView, @NonNull EditText telephoneEditText,
      @NonNull MaterialToolbar toolbar) {
    this.rootView = rootView;
    this.appBarLayout = appBarLayout;
    this.emailEditText = emailEditText;
    this.forgotPasswordTextView = forgotPasswordTextView;
    this.nameEditText = nameEditText;
    this.passwordEditText = passwordEditText;
    this.progressBar = progressBar;
    this.registerButton = registerButton;
    this.rememberMeCheckBox = rememberMeCheckBox;
    this.signInTextView = signInTextView;
    this.telephoneEditText = telephoneEditText;
    this.toolbar = toolbar;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityUserLoginBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityUserLoginBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_user_login, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityUserLoginBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.appBarLayout;
      AppBarLayout appBarLayout = ViewBindings.findChildViewById(rootView, id);
      if (appBarLayout == null) {
        break missingId;
      }

      id = R.id.emailEditText;
      EditText emailEditText = ViewBindings.findChildViewById(rootView, id);
      if (emailEditText == null) {
        break missingId;
      }

      id = R.id.forgotPasswordTextView;
      TextView forgotPasswordTextView = ViewBindings.findChildViewById(rootView, id);
      if (forgotPasswordTextView == null) {
        break missingId;
      }

      id = R.id.nameEditText;
      EditText nameEditText = ViewBindings.findChildViewById(rootView, id);
      if (nameEditText == null) {
        break missingId;
      }

      id = R.id.passwordEditText;
      EditText passwordEditText = ViewBindings.findChildViewById(rootView, id);
      if (passwordEditText == null) {
        break missingId;
      }

      id = R.id.progressBar;
      ProgressBar progressBar = ViewBindings.findChildViewById(rootView, id);
      if (progressBar == null) {
        break missingId;
      }

      id = R.id.registerButton;
      MaterialButton registerButton = ViewBindings.findChildViewById(rootView, id);
      if (registerButton == null) {
        break missingId;
      }

      id = R.id.rememberMeCheckBox;
      CheckBox rememberMeCheckBox = ViewBindings.findChildViewById(rootView, id);
      if (rememberMeCheckBox == null) {
        break missingId;
      }

      id = R.id.signInTextView;
      TextView signInTextView = ViewBindings.findChildViewById(rootView, id);
      if (signInTextView == null) {
        break missingId;
      }

      id = R.id.telephoneEditText;
      EditText telephoneEditText = ViewBindings.findChildViewById(rootView, id);
      if (telephoneEditText == null) {
        break missingId;
      }

      id = R.id.toolbar;
      MaterialToolbar toolbar = ViewBindings.findChildViewById(rootView, id);
      if (toolbar == null) {
        break missingId;
      }

      return new ActivityUserLoginBinding((ConstraintLayout) rootView, appBarLayout, emailEditText,
          forgotPasswordTextView, nameEditText, passwordEditText, progressBar, registerButton,
          rememberMeCheckBox, signInTextView, telephoneEditText, toolbar);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
