// Generated by view binder compiler. Do not edit!
package com.example.vpark.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.vpark.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMainBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ConstraintLayout contentCard;

  @NonNull
  public final LinearLayout getStartedBtn;

  @NonNull
  public final ImageView heroImage;

  @NonNull
  public final ConstraintLayout main;

  @NonNull
  public final ImageView parkIcon;

  @NonNull
  public final TextView subTitleText;

  @NonNull
  public final TextView titleText;

  private ActivityMainBinding(@NonNull ConstraintLayout rootView,
      @NonNull ConstraintLayout contentCard, @NonNull LinearLayout getStartedBtn,
      @NonNull ImageView heroImage, @NonNull ConstraintLayout main, @NonNull ImageView parkIcon,
      @NonNull TextView subTitleText, @NonNull TextView titleText) {
    this.rootView = rootView;
    this.contentCard = contentCard;
    this.getStartedBtn = getStartedBtn;
    this.heroImage = heroImage;
    this.main = main;
    this.parkIcon = parkIcon;
    this.subTitleText = subTitleText;
    this.titleText = titleText;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.contentCard;
      ConstraintLayout contentCard = ViewBindings.findChildViewById(rootView, id);
      if (contentCard == null) {
        break missingId;
      }

      id = R.id.getStartedBtn;
      LinearLayout getStartedBtn = ViewBindings.findChildViewById(rootView, id);
      if (getStartedBtn == null) {
        break missingId;
      }

      id = R.id.heroImage;
      ImageView heroImage = ViewBindings.findChildViewById(rootView, id);
      if (heroImage == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      id = R.id.parkIcon;
      ImageView parkIcon = ViewBindings.findChildViewById(rootView, id);
      if (parkIcon == null) {
        break missingId;
      }

      id = R.id.subTitleText;
      TextView subTitleText = ViewBindings.findChildViewById(rootView, id);
      if (subTitleText == null) {
        break missingId;
      }

      id = R.id.titleText;
      TextView titleText = ViewBindings.findChildViewById(rootView, id);
      if (titleText == null) {
        break missingId;
      }

      return new ActivityMainBinding((ConstraintLayout) rootView, contentCard, getStartedBtn,
          heroImage, main, parkIcon, subTitleText, titleText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
