// Generated by view binder compiler. Do not edit!
package com.example.vpark.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.vpark.R;
import com.google.android.material.card.MaterialCardView;
import com.google.android.material.switchmaterial.SwitchMaterial;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ItemParkingLotBinding implements ViewBinding {
  @NonNull
  private final MaterialCardView rootView;

  @NonNull
  public final TextView lotLocationTextView;

  @NonNull
  public final TextView lotNameTextView;

  @NonNull
  public final SwitchMaterial lotStatusSwitch;

  @NonNull
  public final TextView slotCountTextView;

  private ItemParkingLotBinding(@NonNull MaterialCardView rootView,
      @NonNull TextView lotLocationTextView, @NonNull TextView lotNameTextView,
      @NonNull SwitchMaterial lotStatusSwitch, @NonNull TextView slotCountTextView) {
    this.rootView = rootView;
    this.lotLocationTextView = lotLocationTextView;
    this.lotNameTextView = lotNameTextView;
    this.lotStatusSwitch = lotStatusSwitch;
    this.slotCountTextView = slotCountTextView;
  }

  @Override
  @NonNull
  public MaterialCardView getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemParkingLotBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemParkingLotBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_parking_lot, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemParkingLotBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.lotLocationTextView;
      TextView lotLocationTextView = ViewBindings.findChildViewById(rootView, id);
      if (lotLocationTextView == null) {
        break missingId;
      }

      id = R.id.lotNameTextView;
      TextView lotNameTextView = ViewBindings.findChildViewById(rootView, id);
      if (lotNameTextView == null) {
        break missingId;
      }

      id = R.id.lotStatusSwitch;
      SwitchMaterial lotStatusSwitch = ViewBindings.findChildViewById(rootView, id);
      if (lotStatusSwitch == null) {
        break missingId;
      }

      id = R.id.slotCountTextView;
      TextView slotCountTextView = ViewBindings.findChildViewById(rootView, id);
      if (slotCountTextView == null) {
        break missingId;
      }

      return new ItemParkingLotBinding((MaterialCardView) rootView, lotLocationTextView,
          lotNameTextView, lotStatusSwitch, slotCountTextView);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
