// Generated by view binder compiler. Do not edit!
package com.example.vpark.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.vpark.R;
import com.google.android.material.card.MaterialCardView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ItemUserBillBinding implements ViewBinding {
  @NonNull
  private final MaterialCardView rootView;

  @NonNull
  public final TextView billDate;

  @NonNull
  public final TextView billFinalAmount;

  @NonNull
  public final TextView billParkingType;

  @NonNull
  public final TextView billVehicleNumber;

  private ItemUserBillBinding(@NonNull MaterialCardView rootView, @NonNull TextView billDate,
      @NonNull TextView billFinalAmount, @NonNull TextView billParkingType,
      @NonNull TextView billVehicleNumber) {
    this.rootView = rootView;
    this.billDate = billDate;
    this.billFinalAmount = billFinalAmount;
    this.billParkingType = billParkingType;
    this.billVehicleNumber = billVehicleNumber;
  }

  @Override
  @NonNull
  public MaterialCardView getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemUserBillBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemUserBillBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_user_bill, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemUserBillBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.billDate;
      TextView billDate = ViewBindings.findChildViewById(rootView, id);
      if (billDate == null) {
        break missingId;
      }

      id = R.id.billFinalAmount;
      TextView billFinalAmount = ViewBindings.findChildViewById(rootView, id);
      if (billFinalAmount == null) {
        break missingId;
      }

      id = R.id.billParkingType;
      TextView billParkingType = ViewBindings.findChildViewById(rootView, id);
      if (billParkingType == null) {
        break missingId;
      }

      id = R.id.billVehicleNumber;
      TextView billVehicleNumber = ViewBindings.findChildViewById(rootView, id);
      if (billVehicleNumber == null) {
        break missingId;
      }

      return new ItemUserBillBinding((MaterialCardView) rootView, billDate, billFinalAmount,
          billParkingType, billVehicleNumber);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
