// Generated by view binder compiler. Do not edit!
package com.example.vpark.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.vpark.R;
import com.google.android.material.card.MaterialCardView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ItemBillReportBinding implements ViewBinding {
  @NonNull
  private final MaterialCardView rootView;

  @NonNull
  public final TextView reportAmount;

  @NonNull
  public final TextView reportDate;

  @NonNull
  public final TextView reportOwnerName;

  @NonNull
  public final TextView reportVehicleNumber;

  private ItemBillReportBinding(@NonNull MaterialCardView rootView, @NonNull TextView reportAmount,
      @NonNull TextView reportDate, @NonNull TextView reportOwnerName,
      @NonNull TextView reportVehicleNumber) {
    this.rootView = rootView;
    this.reportAmount = reportAmount;
    this.reportDate = reportDate;
    this.reportOwnerName = reportOwnerName;
    this.reportVehicleNumber = reportVehicleNumber;
  }

  @Override
  @NonNull
  public MaterialCardView getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemBillReportBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemBillReportBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_bill_report, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemBillReportBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.reportAmount;
      TextView reportAmount = ViewBindings.findChildViewById(rootView, id);
      if (reportAmount == null) {
        break missingId;
      }

      id = R.id.reportDate;
      TextView reportDate = ViewBindings.findChildViewById(rootView, id);
      if (reportDate == null) {
        break missingId;
      }

      id = R.id.reportOwnerName;
      TextView reportOwnerName = ViewBindings.findChildViewById(rootView, id);
      if (reportOwnerName == null) {
        break missingId;
      }

      id = R.id.reportVehicleNumber;
      TextView reportVehicleNumber = ViewBindings.findChildViewById(rootView, id);
      if (reportVehicleNumber == null) {
        break missingId;
      }

      return new ItemBillReportBinding((MaterialCardView) rootView, reportAmount, reportDate,
          reportOwnerName, reportVehicleNumber);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
