// Generated by view binder compiler. Do not edit!
package com.example.vpark.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.vpark.R;
import com.google.android.material.card.MaterialCardView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class UserItemParkingLotBinding implements ViewBinding {
  @NonNull
  private final MaterialCardView rootView;

  @NonNull
  public final TextView availableSlotsTextView;

  @NonNull
  public final TextView lotLocationTextView;

  @NonNull
  public final TextView lotNameTextView;

  @NonNull
  public final LinearLayout slotsContainer;

  private UserItemParkingLotBinding(@NonNull MaterialCardView rootView,
      @NonNull TextView availableSlotsTextView, @NonNull TextView lotLocationTextView,
      @NonNull TextView lotNameTextView, @NonNull LinearLayout slotsContainer) {
    this.rootView = rootView;
    this.availableSlotsTextView = availableSlotsTextView;
    this.lotLocationTextView = lotLocationTextView;
    this.lotNameTextView = lotNameTextView;
    this.slotsContainer = slotsContainer;
  }

  @Override
  @NonNull
  public MaterialCardView getRoot() {
    return rootView;
  }

  @NonNull
  public static UserItemParkingLotBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static UserItemParkingLotBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.user_item_parking_lot, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static UserItemParkingLotBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.availableSlotsTextView;
      TextView availableSlotsTextView = ViewBindings.findChildViewById(rootView, id);
      if (availableSlotsTextView == null) {
        break missingId;
      }

      id = R.id.lotLocationTextView;
      TextView lotLocationTextView = ViewBindings.findChildViewById(rootView, id);
      if (lotLocationTextView == null) {
        break missingId;
      }

      id = R.id.lotNameTextView;
      TextView lotNameTextView = ViewBindings.findChildViewById(rootView, id);
      if (lotNameTextView == null) {
        break missingId;
      }

      id = R.id.slotsContainer;
      LinearLayout slotsContainer = ViewBindings.findChildViewById(rootView, id);
      if (slotsContainer == null) {
        break missingId;
      }

      return new UserItemParkingLotBinding((MaterialCardView) rootView, availableSlotsTextView,
          lotLocationTextView, lotNameTextView, slotsContainer);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
